### ISSUE TITLE
Intermittently observing GET on endpoint instead of POST

### ISSUE THREAD

**Issue by AJamesPhillips** [mperdeck/jsnlog.js#65] opened 2018-04-13 12:52 UTC
I suspect this has nothing to do with the JSNLog code but instead related to some error and browser version edge case.

We have an endpoint that works and receives errors from client browsers as expected.  Over the last few months we have received the vast majority of requests here with the POST method.  However very occasionally a GET request will come through.  I can't see anything other than this POST being sent: https://github.com/mperdeck/jsnlog.js/blob/2a89b919592a8708818726e0e9f830c5cd6518c0/jsnlog.ts#L772

Is there a GET being used somewhere else?  Do some browsers resort to a GET if the POST fails or something?

Any thoughts on this?  I would like to understand why this happens as then we can silence the errors or fix and understand any underlying problem.  Many thanks in advance.

**Comment by mperdeck** [comment] 2018-04-22 02:50
Sorry for the late reply. Was overseas.

As you found, jsnlog.js sends log messages at only one place in the code, as POST requests. I have never seen it send GET requests. I have no idea why you are seeing GET requests.

If you find a way to reproduce these GETs, please open a new ticket showing how (maybe using a small test project). Meanwhile, I'll close this ticket because currently it is not actionable.

**Closed by mperdeck** 2018-04-22 02:50 UTC
